# Generated by Django 4.2.16 on 2025-10-15 09:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("is_village_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="HeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nama gambar hero", max_length=200),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Homepage"),
                            ("events", "Kegiatan"),
                            ("news", "Berita"),
                            ("tourism", "Wisata"),
                            ("umkm", "UMKM"),
                            ("organization", "Organisasi"),
                            ("correspondence", "Surat Menyurat"),
                            ("gallery", "Galeri"),
                            ("complaints", "Keluhan"),
                            ("layanan", "Layanan"),
                            ("posyandu", "Posyandu"),
                            ("bantuna", "Bantuna"),
                            ("business", "Bisnis"),
                            ("koperasi", "Koperasi"),
                            ("bumg", "BUMG"),
                            ("layanan_jasa", "Layanan Jasa"),
                        ],
                        default="home",
                        help_text="Halaman yang menggunakan gambar ini",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Gambar hero", upload_to="hero_images/%Y/%m/%d/"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Status aktif"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero Image",
                "verbose_name_plural": "Hero Images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("references", "Data Referensi"),
                            ("beneficiaries", "Penerima Bantuan"),
                            ("business", "Usaha"),
                            ("complaints", "Keluhan"),
                            ("documents", "Dokumen"),
                            ("tourism", "Wisata"),
                            ("posyandu", "Posyandu"),
                            ("news", "Berita"),
                            ("village_profile", "Profil Desa"),
                            ("organization", "Organisasi"),
                            ("layanan", "Layanan"),
                            ("reports", "Laporan"),
                            ("settings", "Pengaturan"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Lihat"),
                            ("add", "Tambah"),
                            ("change", "Ubah"),
                            ("delete", "Hapus"),
                            ("export", "Export"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("codename", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Menu Permission",
                "verbose_name_plural": "Menu Permissions",
                "unique_together": {("module", "action")},
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("admin", "Admin"),
                            ("data_manager", "Data Manager"),
                            ("beneficiary_manager", "Manager Penerima Bantuan"),
                            ("business_manager", "Manager Usaha"),
                            ("complaint_manager", "Manager Keluhan"),
                            ("document_manager", "Manager Dokumen"),
                            ("tourism_manager", "Manager Wisata"),
                            ("posyandu_manager", "Manager Posyandu"),
                            ("news_manager", "Manager Berita"),
                            ("village_profile_manager", "Manager Profil Desa"),
                            ("organization_manager", "Manager Organisasi"),
                            ("karang_taruna_manager", "Manager Karang Taruna"),
                            ("kepemudaan_manager", "Manager Kepemudaan"),
                            ("pkk_manager", "Manager PKK"),
                            ("lembaga_adat_manager", "Manager Lembaga Adat"),
                            ("perangkat_desa_manager", "Manager Perangkat Desa"),
                            ("village_staff", "Staff Desa"),
                            ("moderator", "Moderator"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "menu_permissions",
                    models.ManyToManyField(blank=True, to="core.menupermission"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, to="auth.permission"),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Website Desa Pulosarok", max_length=200),
                ),
                (
                    "site_description",
                    models.TextField(
                        blank=True,
                        help_text="Deskripsi singkat website yang akan ditampilkan di halaman utama",
                        null=True,
                    ),
                ),
                (
                    "site_logo",
                    models.ImageField(blank=True, null=True, upload_to="website/"),
                ),
                (
                    "site_favicon",
                    models.ImageField(blank=True, null=True, upload_to="website/"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("contact_address", models.TextField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light Theme"),
                            ("dark", "Dark Theme"),
                            ("auto", "Auto (System)"),
                        ],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("primary_color", models.CharField(default="#3B82F6", max_length=7)),
                ("secondary_color", models.CharField(default="#10B981", max_length=7)),
                (
                    "default_language",
                    models.CharField(
                        choices=[
                            ("id", "Bahasa Indonesia"),
                            ("en", "English"),
                            ("jv", "Bahasa Jawa"),
                        ],
                        default="id",
                        max_length=5,
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Jakarta", max_length=50)),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                (
                    "google_analytics_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True, null=True)),
                ("allow_registration", models.BooleanField(default=False)),
                ("max_file_upload_size", models.IntegerField(default=10)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Website Settings",
                "verbose_name_plural": "Website Settings",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.role"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "unique_together": {("user", "role")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_id",
                    models.CharField(
                        blank=True,
                        help_text="Secure unique profile identifier",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Foto profil pengguna",
                        null=True,
                        upload_to="user_photos/",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Nomor telepon", max_length=20, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Laki-laki"), ("F", "Perempuan")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="Alamat IP saat login"),
                ),
                ("user_agent", models.TextField(help_text="User agent browser")),
                (
                    "browser",
                    models.CharField(
                        blank=True, help_text="Nama browser", max_length=50, null=True
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, help_text="Sistem operasi", max_length=50, null=True
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True,
                        help_text="Jenis perangkat",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Lokasi berdasarkan IP",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, help_text="Waktu login"),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, help_text="Waktu logout", null=True
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(
                        default=True, help_text="Apakah login berhasil"
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        help_text="Alasan gagal login",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Riwayat Login",
                "verbose_name_plural": "Riwayat Login",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseResetConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nama konfigurasi reset", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Deskripsi konfigurasi", null=True
                    ),
                ),
                (
                    "reset_type",
                    models.CharField(
                        choices=[
                            ("selective", "Reset Selektif"),
                            ("full", "Reset Lengkap"),
                            ("custom", "Reset Kustom"),
                        ],
                        default="selective",
                        max_length=20,
                    ),
                ),
                (
                    "reset_penduduk",
                    models.BooleanField(default=False, help_text="Reset data penduduk"),
                ),
                (
                    "reset_dusun",
                    models.BooleanField(default=False, help_text="Reset data dusun"),
                ),
                (
                    "reset_lorong",
                    models.BooleanField(default=False, help_text="Reset data lorong"),
                ),
                (
                    "reset_rt_rw",
                    models.BooleanField(default=False, help_text="Reset data RT/RW"),
                ),
                (
                    "reset_keluarga",
                    models.BooleanField(default=False, help_text="Reset data keluarga"),
                ),
                (
                    "reset_pelajar",
                    models.BooleanField(default=False, help_text="Reset data pelajar"),
                ),
                (
                    "reset_disabilitas",
                    models.BooleanField(
                        default=False, help_text="Reset data disabilitas"
                    ),
                ),
                (
                    "reset_beneficiaries",
                    models.BooleanField(
                        default=False, help_text="Reset data penerima bantuan"
                    ),
                ),
                (
                    "reset_business",
                    models.BooleanField(default=False, help_text="Reset data usaha"),
                ),
                (
                    "reset_complaints",
                    models.BooleanField(default=False, help_text="Reset data keluhan"),
                ),
                (
                    "reset_documents",
                    models.BooleanField(default=False, help_text="Reset data dokumen"),
                ),
                (
                    "reset_tourism",
                    models.BooleanField(default=False, help_text="Reset data wisata"),
                ),
                (
                    "reset_posyandu",
                    models.BooleanField(default=False, help_text="Reset data posyandu"),
                ),
                (
                    "reset_news",
                    models.BooleanField(default=False, help_text="Reset data berita"),
                ),
                (
                    "reset_organization",
                    models.BooleanField(
                        default=False, help_text="Reset data organisasi"
                    ),
                ),
                (
                    "reset_layanan",
                    models.BooleanField(default=False, help_text="Reset data layanan"),
                ),
                (
                    "reset_letters",
                    models.BooleanField(
                        default=False, help_text="Reset data surat menyurat"
                    ),
                ),
                (
                    "backup_before_reset",
                    models.BooleanField(
                        default=True, help_text="Backup data sebelum reset"
                    ),
                ),
                (
                    "keep_users",
                    models.BooleanField(
                        default=True, help_text="Tetap simpan data pengguna"
                    ),
                ),
                (
                    "keep_settings",
                    models.BooleanField(
                        default=True, help_text="Tetap simpan pengaturan"
                    ),
                ),
                (
                    "keep_media",
                    models.BooleanField(
                        default=False, help_text="Tetap simpan file media"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("running", "Berjalan"),
                            ("completed", "Selesai"),
                            ("failed", "Gagal"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_log",
                    models.TextField(
                        blank=True, help_text="Log eksekusi reset", null=True
                    ),
                ),
                (
                    "error_log",
                    models.TextField(
                        blank=True, help_text="Log error jika ada", null=True
                    ),
                ),
                (
                    "records_deleted",
                    models.JSONField(
                        default=dict, help_text="Jumlah record yang dihapus per tabel"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reset_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_reset_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Database Reset Configuration",
                "verbose_name_plural": "Database Reset Configurations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="roles",
            field=models.ManyToManyField(
                blank=True, through="core.UserRole", to="core.role"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
