# Generated by Django 5.2.7 on 2025-10-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                through="core.UserRole",
                through_fields=("user", "role"),
                to="core.role",
            ),
        ),
    ]
