# Generated by Django 5.2.7 on 2025-10-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customuser_roles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="websitesettings",
            old_name="maintenance_mode",
            new_name="enable_maintenance_mode",
        ),
    ]
