# Generated by Django 5.2.7 on 2025-10-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0003_rename_maintenance_mode_websitesettings_enable_maintenance_mode",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="websitesettings",
            name="email_notifications",
        ),
    ]
