# Generated by Django 5.2.7 on 2025-10-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_email_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="cache_duration",
            field=models.IntegerField(
                default=300, verbose_name="Cache Duration (seconds)"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="cdn_url",
            field=models.URLField(blank=True, null=True, verbose_name="CDN URL"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_cache",
            field=models.BooleanField(default=True, verbose_name="Enable Cache"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_cdn",
            field=models.BooleanField(default=False, verbose_name="Enable CDN"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_gzip_compression",
            field=models.BooleanField(
                default=True, verbose_name="Enable GZIP Compression"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_minify_css",
            field=models.BooleanField(default=False, verbose_name="Minify CSS"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_minify_js",
            field=models.BooleanField(default=False, verbose_name="Minify JavaScript"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_static_cache",
            field=models.BooleanField(default=True, verbose_name="Enable Static Cache"),
        ),
    ]
