# Generated by Django 5.2.7 on 2025-10-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_cache_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="websitesettings",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="meta_keywords",
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="bing_webmaster",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Bing Webmaster"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_facebook_tracking",
            field=models.BooleanField(
                default=False, verbose_name="Enable Facebook Tracking"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_robots_txt",
            field=models.BooleanField(default=True, verbose_name="Enable robots.txt"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_sitemap",
            field=models.BooleanField(default=True, verbose_name="Enable Sitemap"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="facebook_pixel_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Facebook Pixel ID"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="google_search_console",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Google Search Console",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="google_tag_manager_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Google Tag Manager ID",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="og_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="OG Description"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="og_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="website/og/", verbose_name="OG Image"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="og_title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="OG Title"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="robots_content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Robots.txt Content"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="site_author",
            field=models.CharField(
                default="Tim Website Pulosarok",
                max_length=200,
                verbose_name="Site Author",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="site_keywords",
            field=models.TextField(blank=True, null=True, verbose_name="Site Keywords"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="site_language",
            field=models.CharField(
                default="id", max_length=5, verbose_name="Site Language"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="site_title",
            field=models.CharField(
                default="Website Desa Pulosarok",
                max_length=200,
                verbose_name="Site Title",
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="google_analytics_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Google Analytics ID"
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="site_description",
            field=models.TextField(
                blank=True,
                help_text="Deskripsi singkat website yang akan ditampilkan di halaman utama",
                null=True,
                verbose_name="Site Description",
            ),
        ),
    ]
