# Generated by Django 5.2.7 on 2025-10-19 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_seo_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Tambah"),
                            ("update", "Ubah"),
                            ("delete", "Hapus"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view", "Lihat"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("reset", "Reset"),
                            ("backup", "Backup"),
                            ("restore", "Restore"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("user", "User Management"),
                            ("settings", "Settings"),
                            ("dashboard", "Dashboard"),
                            ("references", "Data Referensi"),
                            ("beneficiaries", "Penerima Bantuan"),
                            ("business", "Usaha"),
                            ("complaints", "Keluhan"),
                            ("documents", "Dokumen"),
                            ("tourism", "Wisata"),
                            ("posyandu", "Posyandu"),
                            ("news", "Berita"),
                            ("village_profile", "Profil Desa"),
                            ("organization", "Organisasi"),
                            ("layanan", "Layanan"),
                            ("letters", "Surat Menyurat"),
                            ("system", "Sistem"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("object_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "object_repr",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_activi_user_id_599332_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="core_activi_action_4055cf_idx",
                    ),
                    models.Index(
                        fields=["module", "created_at"],
                        name="core_activi_module_66734e_idx",
                    ),
                ],
            },
        ),
    ]
