# Generated by Django 5.2.7 on 2025-10-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="enable_2fa",
            field=models.BooleanField(default=False, verbose_name="Enable 2FA"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_captcha",
            field=models.BooleanField(default=False, verbose_name="Enable CAPTCHA"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_hsts",
            field=models.BooleanField(default=True, verbose_name="Enable HSTS"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_ssl_redirect",
            field=models.BooleanField(default=True, verbose_name="Enable SSL Redirect"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="hsts_max_age",
            field=models.IntegerField(default=31536000, verbose_name="HSTS Max Age"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="login_timeout",
            field=models.IntegerField(
                default=15, verbose_name="Login Timeout (minutes)"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="max_login_attempts",
            field=models.IntegerField(default=5, verbose_name="Max Login Attempts"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="min_password_length",
            field=models.IntegerField(default=8, verbose_name="Min Password Length"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="password_expiry",
            field=models.IntegerField(
                default=90, verbose_name="Password Expiry (days)"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="require_lowercase",
            field=models.BooleanField(default=True, verbose_name="Require Lowercase"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="require_numbers",
            field=models.BooleanField(default=True, verbose_name="Require Numbers"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="require_symbols",
            field=models.BooleanField(default=False, verbose_name="Require Symbols"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="require_uppercase",
            field=models.BooleanField(default=True, verbose_name="Require Uppercase"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="security_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
                verbose_name="Security Level",
            ),
        ),
    ]
