# Generated by Django 4.2.16 on 2025-10-15 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IbuHamil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tanggal_hpht",
                    models.DateField(help_text="Hari Pertama Haid Terakhir"),
                ),
                (
                    "usia_kehamilan",
                    models.PositiveIntegerField(help_text="Dalam minggu"),
                ),
                ("tanggal_perkiraan_lahir", models.DateField()),
                (
                    "riwayat_kehamilan",
                    models.CharField(
                        choices=[
                            ("1", "Kehamilan Pertama"),
                            ("2", "Kehamilan Kedua"),
                            ("3", "Kehamilan Ketiga"),
                            ("4+", "Kehamilan Keempat atau Lebih"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "berat_badan_sebelum_hamil",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tinggi_badan",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("golongan_darah", models.CharField(blank=True, max_length=5)),
                ("riwayat_penyakit", models.TextField(blank=True)),
                (
                    "risiko_kehamilan",
                    models.CharField(
                        choices=[
                            ("rendah", "Risiko Rendah"),
                            ("tinggi", "Risiko Tinggi"),
                        ],
                        default="rendah",
                        max_length=10,
                    ),
                ),
                ("nomor_buku_kia", models.CharField(blank=True, max_length=50)),
                ("status_aktif", models.BooleanField(default=True)),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ibu Hamil",
                "verbose_name_plural": "Ibu Hamil",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "age_min",
                    models.PositiveIntegerField(
                        blank=True, help_text="Minimum age in years", null=True
                    ),
                ),
                (
                    "age_max",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum age in years", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jenis Pasien",
                "verbose_name_plural": "Jenis Pasien",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Penduduk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("nik", models.CharField(max_length=16, unique=True)),
                ("alamat", models.TextField(blank=True)),
                ("telepon", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Penduduk",
                "verbose_name_plural": "Penduduk",
            },
        ),
        migrations.CreateModel(
            name="PosyanduLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("capacity", models.PositiveIntegerField(default=50)),
                ("facilities", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="posyandu/locations/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("established_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coordinator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinated_posyandu",
                        to="posyandu.penduduk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lokasi Posyandu",
                "verbose_name_plural": "Lokasi Posyandu",
            },
        ),
        migrations.CreateModel(
            name="PosyanduPageHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Posyandu Desa", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Informasi lengkap mengenai kegiatan posyandu dan kesehatan masyarakat",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="page_headers/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Header Halaman Posyandu",
                "verbose_name_plural": "Header Halaman Posyandu",
            },
        ),
        migrations.CreateModel(
            name="StuntingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_ukur", models.DateField()),
                ("usia_bulan", models.PositiveIntegerField()),
                ("tinggi_badan", models.DecimalField(decimal_places=2, max_digits=5)),
                ("berat_badan", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "z_score_tb_u",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Z-Score Tinggi Badan menurut Umur",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "z_score_bb_u",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Z-Score Berat Badan menurut Umur",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "z_score_bb_tb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Z-Score Berat Badan menurut Tinggi Badan",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status_stunting",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("pendek", "Pendek (Stunted)"),
                            ("sangat_pendek", "Sangat Pendek (Severely Stunted)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("asi_eksklusif", models.BooleanField(default=False)),
                (
                    "riwayat_bblr",
                    models.BooleanField(
                        default=False, help_text="Berat Badan Lahir Rendah"
                    ),
                ),
                ("riwayat_penyakit", models.TextField(blank=True)),
                (
                    "intervensi_diberikan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gizi", "Intervensi Gizi"),
                            ("kesehatan", "Intervensi Kesehatan"),
                            ("sanitasi", "Intervensi Sanitasi"),
                            ("edukasi", "Edukasi Keluarga"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hasil_intervensi", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stunting_data",
                        to="posyandu.penduduk",
                    ),
                ),
                (
                    "posyandu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posyandu.posyandulocation",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Stunting",
                "verbose_name_plural": "Data Stunting",
                "ordering": ["-tanggal_ukur"],
            },
        ),
        migrations.CreateModel(
            name="PosyanduSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("pemeriksaan", "Pemeriksaan Rutin"),
                            ("imunisasi", "Imunisasi"),
                            ("penyuluhan", "Penyuluhan"),
                            ("penimbangan", "Penimbangan"),
                            ("vitamin", "Pemberian Vitamin"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("schedule_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("target_participants", models.PositiveIntegerField(default=0)),
                ("actual_participants", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posyandu_location_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="posyandu.posyandulocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jadwal Posyandu",
                "verbose_name_plural": "Jadwal Posyandu",
                "ordering": ["-schedule_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="PemeriksaanIbuHamil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_periksa", models.DateField()),
                (
                    "usia_kehamilan",
                    models.PositiveIntegerField(help_text="Dalam minggu"),
                ),
                ("berat_badan", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tekanan_darah", models.CharField(max_length=20)),
                (
                    "tinggi_fundus",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "lingkar_lengan_atas",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "hemoglobin",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("protein_urin", models.CharField(blank=True, max_length=10)),
                ("tablet_fe", models.BooleanField(default=False)),
                ("imunisasi_tt", models.BooleanField(default=False)),
                ("keluhan", models.TextField(blank=True)),
                ("anjuran", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ibu_hamil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pemeriksaan",
                        to="posyandu.ibuhamil",
                    ),
                ),
                (
                    "pemeriksa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pemeriksaan Ibu Hamil",
                "verbose_name_plural": "Pemeriksaan Ibu Hamil",
                "ordering": ["-tanggal_periksa"],
            },
        ),
        migrations.CreateModel(
            name="NutritionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurement_date", models.DateField()),
                ("age_months", models.PositiveIntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "head_circumference",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "arm_circumference",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "nutrition_status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("kurang", "Kurang Gizi"),
                            ("buruk", "Gizi Buruk"),
                            ("lebih", "Gizi Lebih"),
                            ("stunting", "Stunting"),
                            ("wasting", "Wasting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vitamin_a_given", models.BooleanField(default=False)),
                ("iron_supplement_given", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_data",
                        to="posyandu.penduduk",
                    ),
                ),
                (
                    "posyandu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posyandu.posyandulocation",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Nutrisi",
                "verbose_name_plural": "Data Nutrisi",
                "ordering": ["-measurement_date"],
            },
        ),
        migrations.CreateModel(
            name="Immunization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vaccine_type",
                    models.CharField(
                        choices=[
                            ("bcg", "BCG"),
                            ("hepatitis", "Hepatitis B"),
                            ("polio", "Polio"),
                            ("dpt", "DPT"),
                            ("campak", "Campak"),
                            ("other", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("immunization_date", models.DateField()),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "health_worker",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("next_schedule", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Selesai"),
                            ("pending", "Menunggu"),
                            ("overdue", "Terlambat"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immunizations",
                        to="posyandu.penduduk",
                    ),
                ),
                (
                    "posyandu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posyandu.posyandulocation",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imunisasi",
                "verbose_name_plural": "Imunisasi",
                "ordering": ["-immunization_date"],
            },
        ),
        migrations.AddField(
            model_name="ibuhamil",
            name="penduduk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kehamilan",
                to="posyandu.penduduk",
            ),
        ),
        migrations.AddField(
            model_name="ibuhamil",
            name="posyandu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="posyandu.posyandulocation",
            ),
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_type",
                    models.CharField(
                        choices=[
                            ("balita", "Balita"),
                            ("ibu_hamil", "Ibu Hamil"),
                            ("ibu_menyusui", "Ibu Menyusui"),
                            ("lansia", "Lansia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("visit_date", models.DateField()),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("blood_pressure", models.CharField(blank=True, max_length=20)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("complaints", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("treatment", models.TextField(blank=True)),
                ("next_visit", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="posyandu.penduduk",
                    ),
                ),
                (
                    "posyandu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posyandu.posyandulocation",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rekam Kesehatan",
                "verbose_name_plural": "Rekam Kesehatan",
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="PosyanduKader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jabatan",
                    models.CharField(
                        choices=[
                            ("ketua", "Ketua"),
                            ("wakil_ketua", "Wakil Ketua"),
                            ("sekretaris", "Sekretaris"),
                            ("bendahara", "Bendahara"),
                            ("anggota", "Anggota"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nomor_hp", models.CharField(blank=True, max_length=15)),
                ("tanggal_mulai", models.DateField()),
                ("tanggal_selesai", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("nonaktif", "Non-Aktif"),
                            ("cuti", "Cuti"),
                        ],
                        default="aktif",
                        max_length=10,
                    ),
                ),
                (
                    "sertifikat",
                    models.FileField(
                        blank=True, null=True, upload_to="kader_sertifikat/"
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "penduduk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kader_posyandu",
                        to="posyandu.penduduk",
                    ),
                ),
                (
                    "posyandu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kader",
                        to="posyandu.posyandulocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kader Posyandu",
                "verbose_name_plural": "Kader Posyandu",
                "ordering": ["-created_at"],
                "unique_together": {("penduduk", "posyandu", "jabatan")},
            },
        ),
    ]
