# Generated by Django 5.2.7 on 2025-10-19 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posyandu", "0001_initial"),
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthrecord",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_records",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="ibuhamil",
            name="penduduk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kehamilan",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="immunization",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="immunizations",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="nutritiondata",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutrition_data",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="posyandukader",
            name="penduduk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kader_posyandu",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="posyandulocation",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinated_posyandu",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="stuntingdata",
            name="balita",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stunting_data",
                to="references.penduduk",
            ),
        ),
    ]
