# Generated by Django 4.2.16 on 2025-10-15 09:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("references", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Nomor Surat",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Perihal")),
                ("content", models.TextField(verbose_name="Isi Surat")),
                ("purpose", models.TextField(verbose_name="Tujuan Penggunaan")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Diajukan"),
                            ("in_review", "Sedang Ditinjau"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("completed", "Selesai"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Rendah"),
                            ("normal", "Normal"),
                            ("high", "Tinggi"),
                            ("urgent", "Mendesak"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Prioritas",
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Pengajuan"
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Persetujuan"
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Selesai"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Alasan Penolakan"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Catatan")),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="letter_pdfs/",
                        verbose_name="File PDF",
                    ),
                ),
                (
                    "word_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="letter_docs/",
                        verbose_name="File Word",
                    ),
                ),
                (
                    "public_url",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="URL Publik",
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(default=0, verbose_name="Jumlah Kata"),
                ),
                (
                    "estimated_reading_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Estimasi Waktu Baca (detik)"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="id", max_length=10, verbose_name="Bahasa"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.penduduk",
                        verbose_name="Pemohon",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Disetujui Oleh",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Surat",
                "verbose_name_plural": "Surat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LetterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Nomor Permintaan",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        help_text="Jelaskan untuk apa surat ini digunakan",
                        verbose_name="Tujuan Penggunaan",
                    ),
                ),
                (
                    "detailed_purpose",
                    models.TextField(
                        blank=True,
                        help_text="Penjelasan lebih detail tentang penggunaan surat",
                        verbose_name="Detail Tujuan",
                    ),
                ),
                (
                    "urgency_reason",
                    models.TextField(
                        blank=True,
                        help_text="Jika mendesak, jelaskan alasannya",
                        verbose_name="Alasan Urgensi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Verifikasi"),
                            ("verified", "Terverifikasi"),
                            ("in_progress", "Sedang Diproses"),
                            ("completed", "Selesai"),
                            ("rejected", "Ditolak"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Rendah"),
                            ("normal", "Normal"),
                            ("high", "Tinggi"),
                            ("urgent", "Mendesak"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Prioritas",
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="Catatan Verifikasi"),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Verifikasi"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Alasan Penolakan"),
                ),
                (
                    "rejection_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Penolakan"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Pengajuan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Tanggal Update"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Selesai"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.penduduk",
                        verbose_name="Pemohon",
                    ),
                ),
                (
                    "generated_letter",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_request",
                        to="letters.letter",
                        verbose_name="Surat yang Dihasilkan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permintaan Surat",
                "verbose_name_plural": "Permintaan Surat",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="LetterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nama Jenis Surat"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kode Surat"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="letter_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["docx", "pdf"]
                            )
                        ],
                        verbose_name="File Template",
                    ),
                ),
                (
                    "required_documents",
                    models.TextField(
                        blank=True,
                        help_text="Dokumen yang diperlukan (pisahkan dengan koma)",
                        verbose_name="Dokumen yang Diperlukan",
                    ),
                ),
                (
                    "processing_time_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Waktu Proses (Hari)"
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Biaya"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jenis Surat",
                "verbose_name_plural": "Jenis Surat",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupportingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ktp", "KTP"),
                            ("kk", "Kartu Keluarga"),
                            ("akte", "Akte Kelahiran"),
                            ("ijazah", "Ijazah"),
                            ("surat_keterangan", "Surat Keterangan"),
                            ("foto", "Foto"),
                            ("other", "Lainnya"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Dokumen",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Dokumen"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "file",
                    models.FileField(
                        upload_to="supporting_documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                ]
                            )
                        ],
                        verbose_name="File Dokumen",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ukuran File (bytes)"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Upload"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Terverifikasi"),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="Catatan Verifikasi"),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_documents",
                        to="letters.letterrequest",
                        verbose_name="Permintaan Surat",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diupload Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumen Pendukung",
                "verbose_name_plural": "Dokumen Pendukung",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="LetterWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nama Workflow"),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=list,
                        help_text="Daftar langkah dalam workflow",
                        verbose_name="Langkah-langkah",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Dibuat"
                    ),
                ),
                (
                    "letter_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="letters.lettertype",
                        verbose_name="Jenis Surat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Surat",
                "verbose_name_plural": "Workflow Surat",
                "ordering": ["letter_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="LetterTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Dibuat"),
                            ("submitted", "Diajukan"),
                            ("reviewed", "Ditinjau"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("completed", "Diselesaikan"),
                            ("cancelled", "Dibatalkan"),
                            ("sent", "Dikirim"),
                            ("received", "Diterima"),
                            ("returned", "Dikembalikan"),
                        ],
                        max_length=20,
                        verbose_name="Aksi",
                    ),
                ),
                ("description", models.TextField(verbose_name="Deskripsi")),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="Lokasi"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Catatan")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Alamat IP"
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_history",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dilakukan Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Surat",
                "verbose_name_plural": "Tracking Surat",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="LetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nama Template"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("official", "Surat Resmi"),
                            ("certificate", "Surat Keterangan"),
                            ("recommendation", "Surat Rekomendasi"),
                            ("invitation", "Surat Undangan"),
                            ("notification", "Surat Pemberitahuan"),
                            ("custom", "Template Kustom"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Template",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "content_template",
                    models.TextField(
                        help_text="Gunakan {{variable}} untuk placeholder",
                        verbose_name="Template Konten",
                    ),
                ),
                (
                    "variables",
                    models.TextField(
                        default="{}",
                        help_text="JSON object dengan daftar variabel yang tersedia",
                        verbose_name="Variabel Template",
                    ),
                ),
                (
                    "css_styles",
                    models.TextField(
                        blank=True,
                        help_text="CSS untuk styling template",
                        verbose_name="CSS Styles",
                    ),
                ),
                (
                    "header_template",
                    models.TextField(blank=True, verbose_name="Template Header"),
                ),
                (
                    "footer_template",
                    models.TextField(blank=True, verbose_name="Template Footer"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Template Default"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jumlah Penggunaan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Surat",
                "verbose_name_plural": "Template Surat",
                "ordering": ["-is_default", "-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="LetterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "village_name",
                    models.CharField(
                        default="Desa Pulosarok",
                        max_length=100,
                        verbose_name="Nama Desa",
                    ),
                ),
                (
                    "village_address",
                    models.TextField(
                        default="Kecamatan Pulosarok, Kabupaten Indramayu",
                        verbose_name="Alamat Desa",
                    ),
                ),
                (
                    "village_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telepon Desa"
                    ),
                ),
                (
                    "village_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Desa"
                    ),
                ),
                (
                    "village_website",
                    models.URLField(blank=True, verbose_name="Website Desa"),
                ),
                (
                    "village_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="village_settings/",
                        verbose_name="Logo Desa",
                    ),
                ),
                (
                    "head_of_village_name",
                    models.CharField(max_length=100, verbose_name="Nama Kepala Desa"),
                ),
                (
                    "head_of_village_nip",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="NIP Kepala Desa"
                    ),
                ),
                (
                    "head_of_village_signature_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("image", "Gambar"),
                            ("text", "Teks"),
                        ],
                        default="digital",
                        max_length=20,
                        verbose_name="Jenis Tanda Tangan",
                    ),
                ),
                (
                    "head_of_village_signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signatures/",
                        verbose_name="Gambar Tanda Tangan",
                    ),
                ),
                (
                    "head_of_village_signature_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Teks Tanda Tangan"
                    ),
                ),
                (
                    "secretary_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nama Sekretaris Desa"
                    ),
                ),
                (
                    "secretary_nip",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="NIP Sekretaris"
                    ),
                ),
                (
                    "secretary_signature_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("image", "Gambar"),
                            ("text", "Teks"),
                        ],
                        default="digital",
                        max_length=20,
                        verbose_name="Jenis Tanda Tangan Sekretaris",
                    ),
                ),
                (
                    "secretary_signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signatures/",
                        verbose_name="Gambar Tanda Tangan Sekretaris",
                    ),
                ),
                (
                    "letter_number_format",
                    models.CharField(
                        default="{code}/{number:03d}/{month:02d}/{year}",
                        help_text="Gunakan {code}, {number}, {month}, {year} sebagai placeholder",
                        max_length=100,
                        verbose_name="Format Nomor Surat",
                    ),
                ),
                (
                    "current_year_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Counter Tahun Ini"
                    ),
                ),
                (
                    "reset_counter_yearly",
                    models.BooleanField(
                        default=True, verbose_name="Reset Counter Setiap Tahun"
                    ),
                ),
                (
                    "enable_digital_signature",
                    models.BooleanField(
                        default=True, verbose_name="Aktifkan Tanda Tangan Digital"
                    ),
                ),
                (
                    "signature_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="Sertifikat Digital",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengaturan Surat",
                "verbose_name_plural": "Pengaturan Surat",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="letterrequest",
            name="letter_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="letters.lettertype",
                verbose_name="Jenis Surat",
            ),
        ),
        migrations.AddField(
            model_name="letterrequest",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ditolak Oleh",
            ),
        ),
        migrations.AddField(
            model_name="letterrequest",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Diverifikasi Oleh",
            ),
        ),
        migrations.CreateModel(
            name="LetterRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("external", "Eksternal"),
                            ("government", "Instansi Pemerintah"),
                            ("private", "Swasta"),
                            ("individual", "Perorangan"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Penerima",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nama Penerima"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Jabatan"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Organisasi/Instansi"
                    ),
                ),
                ("address", models.TextField(verbose_name="Alamat")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telepon"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Penerima Utama"),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("hand_delivery", "Antar Langsung"),
                            ("post", "Pos"),
                            ("email", "Email"),
                            ("fax", "Fax"),
                        ],
                        default="hand_delivery",
                        max_length=20,
                        verbose_name="Metode Pengiriman",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Pengiriman"
                    ),
                ),
                (
                    "received_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Diterima"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penerima Surat",
                "verbose_name_plural": "Penerima Surat",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="LetterNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Perubahan Status"),
                            ("approval_needed", "Perlu Persetujuan"),
                            ("document_uploaded", "Dokumen Diupload"),
                            ("deadline_reminder", "Pengingat Deadline"),
                            ("completion", "Surat Selesai"),
                        ],
                        max_length=20,
                        verbose_name="Tipe Notifikasi",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Judul")),
                ("message", models.TextField(verbose_name="Pesan")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Sudah Dibaca"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Dibuat"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Dibaca"
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Penerima",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifikasi Surat",
                "verbose_name_plural": "Notifikasi Surat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LetterAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("supporting_document", "Dokumen Pendukung"),
                            ("identity_card", "Kartu Identitas"),
                            ("certificate", "Sertifikat"),
                            ("photo", "Foto"),
                            ("other", "Lainnya"),
                        ],
                        max_length=30,
                        verbose_name="Jenis Lampiran",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Lampiran"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "file",
                    models.FileField(
                        upload_to="letter_attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                ]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ukuran File (bytes)"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Wajib"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diunggah Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lampiran Surat",
                "verbose_name_plural": "Lampiran Surat",
                "ordering": ["-is_required", "title"],
            },
        ),
        migrations.AddField(
            model_name="letter",
            name="letter_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="letters.lettertype",
                verbose_name="Jenis Surat",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="letters.lettertemplate",
                verbose_name="Template Surat",
            ),
        ),
        migrations.CreateModel(
            name="LetterApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("auto", "Otomatis"),
                            ("manual", "Manual"),
                            ("committee", "Komite"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Tipe Persetujuan",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Disetujui"),
                ),
                (
                    "approval_notes",
                    models.TextField(blank=True, verbose_name="Catatan Persetujuan"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Persetujuan"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Penyetuju",
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persetujuan Surat",
                "verbose_name_plural": "Persetujuan Surat",
                "ordering": ["-approved_at"],
                "unique_together": {("letter", "approver")},
            },
        ),
    ]
