# Generated by Django 4.2.16 on 2025-10-15 09:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Judul Dokumen"),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contoh: 01/APBDES/2025 atau 05/PERDES/XII/2024",
                        max_length=100,
                        verbose_name="Nomor Dokumen",
                    ),
                ),
                (
                    "document_year",
                    models.IntegerField(
                        default=2025,
                        help_text="Tahun terbit dokumen",
                        verbose_name="Tahun Dokumen",
                    ),
                ),
                ("description", models.TextField(default="", verbose_name="Deskripsi")),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Ringkasan singkat untuk tampilan publik",
                        verbose_name="Ringkasan",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx", "xlsx", "xls"]
                            )
                        ],
                        verbose_name="File Dokumen",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="Ukuran File (bytes)"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Gambar cover untuk dokumen (opsional)",
                        null=True,
                        upload_to="documents/thumbnails/%Y/%m/",
                        verbose_name="Thumbnail/Cover",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Sedang Ditinjau"),
                            ("published", "Dipublikasikan"),
                            ("archived", "Diarsipkan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Centang untuk menampilkan dokumen di halaman publik",
                        verbose_name="Tampilkan di Public",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Tampilkan di halaman utama",
                        verbose_name="Dokumen Unggulan",
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="Jumlah Download"),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="Jumlah Dilihat"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Pisahkan dengan koma. Contoh: anggaran, 2025, keuangan",
                        max_length=255,
                        verbose_name="Tag",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Publikasi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Dibuat"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Tanggal Diupdate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumen",
                "verbose_name_plural": "Dokumen",
                "ordering": ["-document_year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nama Kategori"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("apbdes", "APBDES (Anggaran Pendapatan dan Belanja Desa)"),
                            ("realisasi_anggaran", "Laporan Realisasi Anggaran"),
                            ("dana_desa", "Info Dana Desa (DD & ADD)"),
                            ("perdes", "Peraturan Desa (Perdes)"),
                            ("perkades", "Peraturan Kepala Desa (Perkades)"),
                            ("sk_kades", "Surat Keputusan Kepala Desa"),
                            ("profil_desa", "Profil Desa & Kelurahan (Prodeskel)"),
                            ("data_kependudukan", "Data Kependudukan Agregat"),
                            ("peta_desa", "Peta Desa"),
                            ("lppd", "Laporan Penyelenggaraan Pemerintahan Desa"),
                            ("musdes", "Notulensi Musyawarah Desa"),
                            ("laporan_lainnya", "Laporan Lainnya"),
                            ("lainnya", "Dokumen Lainnya"),
                        ],
                        max_length=50,
                        verbose_name="Jenis Kategori",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "icon",
                    models.CharField(
                        default="fa-file",
                        max_length=50,
                        verbose_name="Icon (FontAwesome)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Urutan Tampilan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategori Dokumen",
                "verbose_name_plural": "Kategori Dokumen",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentDownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "downloaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Waktu Download"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_logs",
                        to="documents.document",
                        verbose_name="Dokumen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Download",
                "verbose_name_plural": "Log Download",
                "ordering": ["-downloaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nama")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("comment", models.TextField(verbose_name="Komentar")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Disetujui"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tanggal"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="documents.document",
                        verbose_name="Dokumen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Komentar Dokumen",
                "verbose_name_plural": "Komentar Dokumen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="documents.documentcategory",
                verbose_name="Kategori",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Diupload Oleh",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["category", "status"], name="documents_d_categor_0ec696_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_year"], name="documents_d_documen_549771_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["-created_at"], name="documents_d_created_71dced_idx"
            ),
        ),
    ]
