# Generated by Django 4.2.16 on 2025-10-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ukm",
            name="foto_usaha",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/umkm/",
                verbose_name="Foto Usaha",
            ),
        ),
        migrations.AddField(
            model_name="ukm",
            name="logo_usaha",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/umkm/logos/",
                verbose_name="Logo Usaha",
            ),
        ),
        migrations.AddField(
            model_name="ukm",
            name="whatsapp",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Nomor WhatsApp"
            ),
        ),
    ]
