# Generated by Django 4.2.16 on 2025-10-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_ukm_foto_usaha_ukm_logo_usaha_ukm_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/images/",
                verbose_name="Gambar Bisnis",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/logos/",
                verbose_name="Logo Bisnis",
            ),
        ),
    ]
