# Generated by Django 4.2.16 on 2025-10-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_business_image_business_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="bumg",
            name="foto_bumg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/bumg/",
                verbose_name="Foto BUMG",
            ),
        ),
        migrations.AddField(
            model_name="bumg",
            name="logo_bumg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/bumg/logos/",
                verbose_name="Logo BUMG",
            ),
        ),
        migrations.AddField(
            model_name="koperasi",
            name="foto_koperasi",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/koperasi/",
                verbose_name="Foto Koperasi",
            ),
        ),
        migrations.AddField(
            model_name="koperasi",
            name="logo_koperasi",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/koperasi/logos/",
                verbose_name="Logo Koperasi",
            ),
        ),
        migrations.AddField(
            model_name="layananjasa",
            name="foto_layanan",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/layanan/",
                verbose_name="Foto Layanan",
            ),
        ),
        migrations.AddField(
            model_name="layananjasa",
            name="logo_layanan",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/layanan/logos/",
                verbose_name="Logo Layanan",
            ),
        ),
    ]
