# Generated by Django 4.2.16 on 2025-10-17 13:28

import business.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "business",
            "0004_bumg_foto_bumg_bumg_logo_bumg_koperasi_foto_koperasi_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bumg",
            name="foto_bumg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/bumg/",
                validators=[business.validators.validate_image_file],
                verbose_name="Foto BUMG",
            ),
        ),
        migrations.AlterField(
            model_name="bumg",
            name="logo_bumg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/bumg/logos/",
                validators=[business.validators.validate_logo_file],
                verbose_name="Logo BUMG",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/images/",
                validators=[business.validators.validate_image_file],
                verbose_name="Gambar Bisnis",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/logos/",
                validators=[business.validators.validate_logo_file],
                verbose_name="Logo Bisnis",
            ),
        ),
        migrations.AlterField(
            model_name="koperasi",
            name="foto_koperasi",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/koperasi/",
                validators=[business.validators.validate_image_file],
                verbose_name="Foto Koperasi",
            ),
        ),
        migrations.AlterField(
            model_name="koperasi",
            name="logo_koperasi",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/koperasi/logos/",
                validators=[business.validators.validate_logo_file],
                verbose_name="Logo Koperasi",
            ),
        ),
        migrations.AlterField(
            model_name="layananjasa",
            name="foto_layanan",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/layanan/",
                validators=[business.validators.validate_image_file],
                verbose_name="Foto Layanan",
            ),
        ),
        migrations.AlterField(
            model_name="layananjasa",
            name="logo_layanan",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/layanan/logos/",
                validators=[business.validators.validate_logo_file],
                verbose_name="Logo Layanan",
            ),
        ),
        migrations.AlterField(
            model_name="ukm",
            name="foto_usaha",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/umkm/",
                validators=[business.validators.validate_image_file],
                verbose_name="Foto Usaha",
            ),
        ),
        migrations.AlterField(
            model_name="ukm",
            name="logo_usaha",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="business/umkm/logos/",
                validators=[business.validators.validate_logo_file],
                verbose_name="Logo Usaha",
            ),
        ),
    ]
