# Generated by Django 4.2.16 on 2025-10-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0005_alter_bumg_foto_bumg_alter_bumg_logo_bumg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bumg",
            name="telepon",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="koperasi",
            name="telepon",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="layananjasa",
            name="telepon",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="ukm",
            name="telepon",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
