# Generated by Django 4.2.16 on 2025-10-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0006_alter_bumg_telepon_alter_koperasi_telepon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bumg",
            name="tanggal_sk",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="koperasi",
            name="tanggal_berdiri",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ukm",
            name="tanggal_mulai",
            field=models.DateField(blank=True, null=True),
        ),
    ]
