# Generated by Django 4.2.16 on 2025-10-17 16:01

import business.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "business",
            "0007_alter_bumg_tanggal_sk_alter_koperasi_tanggal_berdiri_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_type",
                    models.CharField(
                        choices=[
                            ("umkm", "UMKM"),
                            ("koperasi", "Koperasi"),
                            ("bumg", "BUMG"),
                            ("layanan_jasa", "Layanan Jasa"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Bisnis",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=200, verbose_name="Nama Bisnis"),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=200, verbose_name="Nama Pemilik"),
                ),
                (
                    "owner_nik",
                    models.CharField(max_length=16, verbose_name="NIK Pemilik"),
                ),
                (
                    "owner_phone",
                    models.CharField(max_length=20, verbose_name="No. Telepon"),
                ),
                (
                    "owner_email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                ("owner_address", models.TextField(verbose_name="Alamat Pemilik")),
                ("business_address", models.TextField(verbose_name="Alamat Bisnis")),
                (
                    "business_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telepon Bisnis"
                    ),
                ),
                (
                    "business_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Bisnis"
                    ),
                ),
                (
                    "business_description",
                    models.TextField(verbose_name="Deskripsi Bisnis"),
                ),
                (
                    "skala_usaha",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mikro", "Mikro"),
                            ("kecil", "Kecil"),
                            ("menengah", "Menengah"),
                        ],
                        max_length=20,
                        verbose_name="Skala Usaha",
                    ),
                ),
                (
                    "jenis_usaha",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Jenis Usaha"
                    ),
                ),
                (
                    "ketua",
                    models.CharField(blank=True, max_length=200, verbose_name="Ketua"),
                ),
                (
                    "sekretaris",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Sekretaris"
                    ),
                ),
                (
                    "bendahara",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bendahara"
                    ),
                ),
                (
                    "jumlah_anggota",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Jumlah Anggota"
                    ),
                ),
                (
                    "modal_dasar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Modal Dasar",
                    ),
                ),
                (
                    "direktur",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Direktur"
                    ),
                ),
                (
                    "komisaris",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Komisaris"
                    ),
                ),
                (
                    "jumlah_karyawan",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Jumlah Karyawan"
                    ),
                ),
                (
                    "bidang_usaha",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bidang Usaha"
                    ),
                ),
                (
                    "penyedia",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Penyedia"
                    ),
                ),
                (
                    "kategori_layanan",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Kategori Layanan"
                    ),
                ),
                (
                    "tarif_layanan",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Tarif Layanan",
                    ),
                ),
                (
                    "business_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="business_registrations/photos/",
                        validators=[business.validators.validate_image_file],
                        verbose_name="Foto Bisnis",
                    ),
                ),
                (
                    "business_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="business_registrations/logos/",
                        validators=[business.validators.validate_logo_file],
                        verbose_name="Logo Bisnis",
                    ),
                ),
                (
                    "additional_documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="business_registrations/documents/",
                        verbose_name="Dokumen Tambahan",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Persetujuan"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("under_review", "Sedang Ditinjau"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Catatan Admin"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Disetujui"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Daftar"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Tanggal Update"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Disetujui Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pendaftaran Bisnis",
                "verbose_name_plural": "Pendaftaran Bisnis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessRegistrationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="business_registrations/images/",
                        validators=[business.validators.validate_image_file],
                        verbose_name="Gambar",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Keterangan"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Gambar Utama"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Upload"
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="business.businessregistration",
                        verbose_name="Pendaftaran",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gambar Pendaftaran",
                "verbose_name_plural": "Gambar Pendaftaran",
            },
        ),
    ]
