# Generated by Django 4.2.16 on 2025-10-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0008_businessregistration_businessregistrationimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessregistration",
            name="business_video",
            field=models.FileField(
                blank=True,
                help_text="Upload video promosi bisnis (MP4, AVI, MOV)",
                null=True,
                upload_to="business_registrations/videos/",
                verbose_name="Video Bisnis",
            ),
        ),
        migrations.AddField(
            model_name="businessregistration",
            name="facebook_url",
            field=models.URLField(
                blank=True, help_text="Link Facebook bisnis", verbose_name="Facebook"
            ),
        ),
        migrations.AddField(
            model_name="businessregistration",
            name="instagram_url",
            field=models.URLField(
                blank=True, help_text="Link Instagram bisnis", verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="businessregistration",
            name="tiktok_url",
            field=models.URLField(
                blank=True, help_text="Link TikTok bisnis", verbose_name="TikTok"
            ),
        ),
        migrations.AddField(
            model_name="businessregistration",
            name="twitter_url",
            field=models.URLField(
                blank=True, help_text="Link Twitter bisnis", verbose_name="Twitter"
            ),
        ),
        migrations.AddField(
            model_name="businessregistration",
            name="website_url",
            field=models.URLField(
                blank=True, help_text="Link website bisnis", verbose_name="Website"
            ),
        ),
        migrations.AddField(
            model_name="businessregistration",
            name="youtube_url",
            field=models.URLField(
                blank=True, help_text="Link YouTube bisnis", verbose_name="YouTube"
            ),
        ),
    ]
