# Generated by Django 5.2.7 on 2025-10-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0009_businessregistration_business_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="koperasi",
            name="bidang_usaha",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Bidang Usaha"
            ),
        ),
        migrations.AddField(
            model_name="koperasi",
            name="jenis_usaha",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Jenis Usaha"
            ),
        ),
    ]
