# Generated by Django 5.2.7 on 2025-10-19 02:45

import business.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0010_koperasi_bidang_usaha_koperasi_jenis_usaha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layananjasa",
            name="sertifikat",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="business/layanan/sertifikat/",
                validators=[business.validators.validate_image_file],
                verbose_name="Sertifikat",
            ),
        ),
    ]
