# Generated by Django 4.2.16 on 2025-10-16 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0001_initial"),
        ("village_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="villageofficial",
            name="penduduk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="official_positions",
                to="references.penduduk",
                verbose_name="Data Penduduk",
            ),
        ),
    ]
