"""
Django settings for pulosarok_website project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-your-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
# Set to True for development, False for production
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'  # Production mode - set DEBUG=True in .env for development

# Production settings untuk pulosarok.my.id
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0,pulosarok.my.id,www.pulosarok.my.id').split(',')

# Application definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'django.contrib.humanize',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'django_extensions',
    'widget_tweaks',
    'corsheaders',
    'import_export',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_summernote',  # WYSIWYG editor
]

LOCAL_APPS = [
    'core',
    'admin_panel',
    'beneficiaries',
    'business',
    'complaints',
    'documents',
    'layanan',
    'news',
    'organization',
    'posyandu',
    'references',
    'letters',
    'tourism',
    'village_profile',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.maintenance_middleware.MaintenanceModeMiddleware',  # Maintenance mode - harus di atas middleware lain
    'core.middleware.RoleBasedAccessMiddleware',
    'core.middleware.CurrentUserMiddleware',  # Current user tracking for activity logging
    'core.middleware.SecurityMiddleware',  # Security settings middleware
    'core.maintenance_middleware.AutoCacheClearMiddleware',
    'admin_panel.activity_middleware.ActivityLoggingMiddleware',  # Activity logging
]

# Tambahkan Security Middleware untuk Production
if not DEBUG and os.getenv('ENVIRONMENT', 'development').lower() == 'production':
    MIDDLEWARE.extend([
        'core.security_middleware.SecurityMiddleware',
        'core.security_middleware.IPBlockingMiddleware',
        'core.security_middleware.RequestLoggingMiddleware',
    ])

ROOT_URLCONF = 'pulosarok_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.website_settings',
                'news.context_processors.latest_news',
                'village_profile.context_processors.village_profile',
                'admin_panel.context_processors.admin_utilities',  # Admin utilities
            ],
        },
    },
]

WSGI_APPLICATION = 'pulosarok_website.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database configuration - PostgreSQL only
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME', 'postgres'),
        'USER': os.getenv('DATABASE_USER', 'postgres'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', 'root'),
        'HOST': os.getenv('DATABASE_HOST', 'localhost'),
        'PORT': os.getenv('DATABASE_PORT', '5432'),
    }
}

# Connection pooling for production
CONN_MAX_AGE = int(os.getenv('CONN_MAX_AGE', '600'))

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# Custom User Model
AUTH_USER_MODEL = 'core.CustomUser'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'id-id'
TIME_ZONE = 'Asia/Jakarta'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Site ID
SITE_ID = 1

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# CORS Settings
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'https://pulosarok.my.id,https://www.pulosarok.my.id').split(',')
CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'True').lower() == 'true'
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@pulosarok.my.id')

# ==================== ADVANCED SECURITY SETTINGS ====================
# Security settings yang berbeda untuk Development dan Production
# Production mode: DEBUG=False atau ENVIRONMENT=production

# Deteksi mode production
IS_PRODUCTION = not DEBUG and os.getenv('ENVIRONMENT', 'development').lower() == 'production'

# ===== SSL/HTTPS Security (HANYA PRODUCTION) =====
if IS_PRODUCTION:
    # Force HTTPS redirect
    SECURE_SSL_REDIRECT = True
    
    # HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = 31536000  # 1 tahun
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Secure Cookies
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    
    # SSL Proxy Header (untuk reverse proxy seperti Nginx)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # Development mode - HTTP allowed
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_PROXY_SSL_HEADER = None

# ===== Browser Security Headers (SELALU AKTIF) =====
# XSS Protection
SECURE_BROWSER_XSS_FILTER = True

# Prevent MIME-sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Clickjacking Protection
X_FRAME_OPTIONS = 'DENY'

# Referrer Policy (PRODUCTION ONLY)
if IS_PRODUCTION:
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
else:
    SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# ===== Content Security Policy (PRODUCTION ONLY) =====
if IS_PRODUCTION:
    # Aktifkan CSP middleware di production
    CSP_ENABLED = True
else:
    CSP_ENABLED = False

# ===== Session Security =====
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Strict' if IS_PRODUCTION else 'Lax'  # Strict CSRF protection in production
SESSION_COOKIE_NAME = 'pulosarok_sessionid'  # Custom session cookie name (security through obscurity)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Database-backed sessions

# Session timeout settings
if IS_PRODUCTION:
    SESSION_COOKIE_AGE = 3600  # 1 hour in production
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True
    SESSION_SAVE_EVERY_REQUEST = True  # Extend session on each request
else:
    SESSION_COOKIE_AGE = 86400  # 24 hours in development
    SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# ===== CSRF Security =====
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF token
CSRF_COOKIE_SAMESITE = 'Strict' if IS_PRODUCTION else 'Lax'
CSRF_COOKIE_NAME = 'pulosarok_csrftoken'  # Custom CSRF cookie name
CSRF_USE_SESSIONS = IS_PRODUCTION  # Store CSRF token in session (more secure)
CSRF_COOKIE_AGE = 31449600  # 1 year

# Trusted origins for CSRF (PRODUCTION)
if IS_PRODUCTION:
    CSRF_TRUSTED_ORIGINS = [
        'https://pulosarok.my.id',
        'https://www.pulosarok.my.id',
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ]

# Tambahan CSRF dari environment variable
env_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if env_csrf_origins:
    CSRF_TRUSTED_ORIGINS.extend(env_csrf_origins.split(','))

# Cache Configuration - PRODUCTION MODE (Dummy Cache for Development)
CACHES = {
    'default': {
        'BACKEND': os.getenv('CACHE_BACKEND', 'django.core.cache.backends.dummy.DummyCache'),
    }
}

# Cache Middleware Configuration
CACHE_MIDDLEWARE_SECONDS = int(os.getenv('CACHE_MIDDLEWARE_SECONDS', '300'))
CACHE_MIDDLEWARE_KEY_PREFIX = os.getenv('CACHE_MIDDLEWARE_KEY_PREFIX', 'pulosarok')
CACHE_MIDDLEWARE_ALIAS = 'default'

# Template cache settings - Disable template caching for development
# Note: Cannot set both loaders and app_dirs, so we'll use a different approach
# TEMPLATES[0]['OPTIONS']['loaders'] = [
#     ('django.template.loaders.filesystem.Loader',),
#     ('django.template.loaders.app_directories.Loader',),
# ]

# Disable template caching
TEMPLATES[0]['OPTIONS']['debug'] = True

# Logging Configuration - Production (DISABLED - akan menggunakan konfigurasi di bawah)

# ===== File Upload Security =====
# Batasi ukuran file upload untuk mencegah DoS attack
if IS_PRODUCTION:
    FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB untuk production
    DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
    DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # Limit jumlah field untuk mencegah DoS
else:
    FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB untuk development
    DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760

# Permissions untuk uploaded files
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Allowed file extensions (whitelist approach)
ALLOWED_UPLOAD_EXTENSIONS = [
    'jpg', 'jpeg', 'png', 'gif', 'webp', 'svg',  # Images
    'pdf', 'doc', 'docx', 'xls', 'xlsx',  # Documents
    'zip', 'rar',  # Archives
]

# ===== Password Security =====
# Additional password requirements for production
if IS_PRODUCTION:
    AUTH_PASSWORD_VALIDATORS.append({
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Minimum 12 karakter untuk production
        }
    })

# Password hashing algorithm (Argon2 lebih aman)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',  # Most secure
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Admin Configuration
ADMIN_URL = os.getenv('ADMIN_URL', 'admin-panel/')
LOGIN_URL = os.getenv('LOGIN_URL', '/custom-login-redirect/')
LOGIN_REDIRECT_URL = os.getenv('LOGIN_REDIRECT_URL', '/admin-panel/')
LOGOUT_REDIRECT_URL = os.getenv('LOGOUT_REDIRECT_URL', '/admin-panel/login/')

# Simple settings for development

# API Keys

# WhiteNoise Configuration - Disabled for deployment mode
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ==================== ADDITIONAL PRODUCTION SETTINGS ====================

# Content Security Policy
CSP_DEFAULT_SRC = os.getenv('CSP_DEFAULT_SRC', "'self'")
CSP_SCRIPT_SRC = os.getenv('CSP_SCRIPT_SRC', "'self' 'unsafe-inline'")
CSP_STYLE_SRC = os.getenv('CSP_STYLE_SRC', "'self' 'unsafe-inline'")
CSP_IMG_SRC = os.getenv('CSP_IMG_SRC', "'self' data: https:")
CSP_FONT_SRC = os.getenv('CSP_FONT_SRC', "'self'")
CSP_CONNECT_SRC = os.getenv('CSP_CONNECT_SRC', "'self'")

# Rate Limiting
RATE_LIMIT_ENABLED = os.getenv('RATE_LIMIT_ENABLED', 'True').lower() == 'true'
RATE_LIMIT_REQUESTS = int(os.getenv('RATE_LIMIT_REQUESTS', '100'))
RATE_LIMIT_WINDOW = int(os.getenv('RATE_LIMIT_WINDOW', '3600'))

# Performance Settings
CONN_MAX_AGE = int(os.getenv('CONN_MAX_AGE', '600'))
CONN_MAX_AGE_OPTIONS = int(os.getenv('CONN_MAX_AGE_OPTIONS', '600'))

# Redis Configuration
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
REDIS_CACHE_URL = os.getenv('REDIS_CACHE_URL', 'redis://127.0.0.1:6379/1')

# Monitoring and Analytics
GOOGLE_ANALYTICS_ID = os.getenv('GOOGLE_ANALYTICS_ID', '')
GOOGLE_TAG_MANAGER_ID = os.getenv('GOOGLE_TAG_MANAGER_ID', '')

# Backup Configuration
BACKUP_ENABLED = os.getenv('BACKUP_ENABLED', 'True').lower() == 'true'
BACKUP_LOCATION = os.getenv('BACKUP_LOCATION', '/var/backups/pulosarok/')
BACKUP_RETENTION_DAYS = int(os.getenv('BACKUP_RETENTION_DAYS', '30'))

# SSL/TLS Configuration
SSL_CERT_PATH = os.getenv('SSL_CERT_PATH', '/etc/ssl/certs/pulosarok.crt')
SSL_KEY_PATH = os.getenv('SSL_KEY_PATH', '/etc/ssl/private/pulosarok.key')

# Error Reporting
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
ERROR_REPORTING = os.getenv('ERROR_REPORTING', 'True').lower() == 'true'

# Maintenance Mode
MAINTENANCE_MODE = os.getenv('MAINTENANCE_MODE', 'False').lower() == 'true'
MAINTENANCE_MODE_IGNORE_ADMIN = os.getenv('MAINTENANCE_MODE_IGNORE_ADMIN', 'True').lower() == 'true'
MAINTENANCE_MODE_IGNORE_STAFF = os.getenv('MAINTENANCE_MODE_IGNORE_STAFF', 'True').lower() == 'true'

# Security Monitoring
SECURITY_MONITORING = os.getenv('SECURITY_MONITORING', 'True').lower() == 'true'
INTRUSION_DETECTION = os.getenv('INTRUSION_DETECTION', 'True').lower() == 'true'
MALWARE_SCANNING = os.getenv('MALWARE_SCANNING', 'True').lower() == 'true'
VULNERABILITY_SCANNING = os.getenv('VULNERABILITY_SCANNING', 'True').lower() == 'true'

# Compliance and Auditing
AUDIT_LOGGING = os.getenv('AUDIT_LOGGING', 'True').lower() == 'true'
COMPLIANCE_MODE = os.getenv('COMPLIANCE_MODE', 'True').lower() == 'true'
DATA_RETENTION_DAYS = int(os.getenv('DATA_RETENTION_DAYS', '2555'))
PRIVACY_MODE = os.getenv('PRIVACY_MODE', 'True').lower() == 'true'

# Environment Detection
ENVIRONMENT = os.getenv('ENVIRONMENT', 'production')
DEPLOYMENT_MODE = os.getenv('DEPLOYMENT_MODE', 'production')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'error.log'),
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'admin_panel': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ==================== DJANGO SUMMERNOTE CONFIGURATION ====================

# Summernote configuration
SUMMERNOTE_THEME = 'bs4'  # Bootstrap 4 theme
SUMMERNOTE_CONFIG = {
    # Using SummernoteWidget - iframe mode, default
    'iframe': True,
    'summernote': {
        # As an example, using Summernote's air mode
        'airMode': False,
        'width': '100%',
        'height': '300',
        'lang': 'id-ID',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
        'popover': {
            'image': [
                ['image', ['resizeFull', 'resizeHalf', 'resizeQuarter', 'resizeNone']],
                ['float', ['floatLeft', 'floatRight', 'floatNone']],
                ['remove', ['removeMedia']]
            ],
            'link': [
                ['link', ['linkDialogShow', 'unlink']]
            ],
            'table': [
                ['add', ['addRowDown', 'addRowUp', 'addColLeft', 'addColRight']],
                ['delete', ['deleteRow', 'deleteCol', 'deleteTable']],
            ],
            'air': [
                ['color', ['color']],
                ['font', ['bold', 'underline', 'clear']]
            ]
        },
        'codemirror': {
            'mode': 'htmlmixed',
            'lineNumbers': 'true',
            'theme': 'monokai',
        },
    },
    # Require users to be authenticated for uploading attachments.
    'attachment_require_authentication': True,
    # Set `upload_to` function for attachments.
    'attachment_upload_to': 'summernote_attachments/',
    # Set storage class for attachments.
    'attachment_storage_class': 'django.core.files.storage.DefaultStorage',
    # Set model for attachments.
    'attachment_model': 'django_summernote.Attachment',
    # You can completely disable attachment feature.
    'disable_attachment': False,
    # Set to `True` to return attachment paths in absolute URIs.
    'attachment_absolute_uri': False,
    'test_cookie': 'summernote_test_cookie',
    'common': {
        # Disable attachment feature.
        'disable_attachment': False,
    },
    'css': (
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.40.0/theme/monokai.min.css',
    ),
    'js': (
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.40.0/mode/xml/xml.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.40.0/mode/htmlmixed/htmlmixed.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.40.0/mode/css/css.min.js',
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.40.0/mode/javascript/javascript.min.js',
    ),
}

# ==================== MEDIA FILES CONFIGURATION ====================

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# ==================== CACHE CONFIGURATION ====================
# Cache configuration untuk mengurangi memory usage
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# Cache timeout (dalam detik)
CACHE_TIMEOUT = 300  # 5 menit

# ==================== MEMORY OPTIMIZATION ====================
# Optimasi untuk mengurangi memory usage
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Database query optimization
USE_TZ = True
TIME_ZONE = 'Asia/Jakarta'

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

# ==================== ERROR HANDLERS ====================
# Custom error handlers untuk production
if not DEBUG:
    # Import error views
    from core import error_views
    
    # Set custom error handlers
    handler404 = error_views.custom_404
    handler500 = error_views.custom_500
    handler403 = error_views.custom_403
    handler400 = error_views.custom_400

# ==================== POSTGRESQL OPTIMIZATION ====================
# PostgreSQL optimizations are configured in DATABASES above

