# Generated by Django 5.2.7 on 2025-10-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="penduduk",
            name="email",
        ),
    ]
